import React from 'react';
import AdminNavbar from '../../components/AdminNavbar';
import ReportsTab from '../../components/ReportsTab';

export default function AdminReportsPage() {
  return (
    <div className="min-h-screen bg-[#BDD8E9]">
      <AdminNavbar />

      <main className="p-8 max-w-7xl mx-auto">
        <div className="flex justify-between items-end mb-8">
          <div>
            <h1 className="text-2xl font-display font-bold text-[#001D39]">AI Credibility Reports</h1>
            <p className="text-[#49769F] font-body text-[14px] mt-1">Forensic analysis generated by Agent-B (Claude-3-Sonnet).</p>
          </div>
        </div>
        <div className="bg-white rounded-xl shadow-sm overflow-hidden min-h-[500px] border border-[#7BBDE8]">
          <ReportsTab />
        </div>
      </main>
    </div>
  );
}
