import { useState, useEffect } from 'react'
import { api } from '../config'

function Label({ children }) {
  return <label className="block text-[10px] font-display font-bold uppercase tracking-[0.08em] text-[#6EA2B3] mb-1.5">{children}</label>;
}

export default function ReportsTab() {
  const [reports, setReports] = useState([])
  const [error, setError] = useState('')

  useEffect(() => {
    api.get('/api/admin/reports')
      .then(setReports)
      .catch(e => setError('Failed to load reports: ' + e.message))
  }, [])

  return (
    <div className="p-8">
      <div className="flex justify-between items-center mb-10">
        <div>
          <h3 className="text-2xl font-display font-bold text-[#001D39]">Credibility Forensics</h3>
          <p className="text-[#49769F] font-body text-[14px]">AI-generated summaries of proctored sessions.</p>
        </div>
        {error && <span className="text-red-500 font-bold text-[12px]">⚠️ {error}</span>}
      </div>

      <div className="grid grid-cols-1 gap-6">
        {reports.length === 0 ? (
          <div className="text-center py-20 border-2 border-dashed border-[#7BBDE8] rounded-2xl text-[#6EA2B3] font-body text-[14px]">
            No forensic reports have been generated by the AI agent yet.
          </div>
        ) : (
          reports.map(r => (
            <div key={r.id} className="bg-white border border-[#7BBDE8] rounded-[24px] p-8 shadow-sm hover:shadow-md transition-all group">
              <div className="flex justify-between items-start mb-6">
                <div className="flex items-center gap-4">
                  <div className="w-12 h-12 bg-[#BDD8E9] rounded-2xl flex items-center justify-center text-xl">📊</div>
                  <div>
                    <h4 className="font-display font-bold text-[#001D39] text-[18px]">{r.student_name}</h4>
                    <p className="text-[#49769F] text-[12px] font-black uppercase tracking-widest">{r.exam_name}</p>
                  </div>
                </div>
                <div className="text-right">
                  <div className={`px-4 py-1.5 rounded-full text-[11px] font-black uppercase tracking-widest border mb-2 inline-block ${
                    r.verdict === 'CLEAR' ? 'bg-[#F0FDFA] text-[#14B8A6] border-[#14B8A6]/20' : 
                    r.verdict === 'FLAGGED' ? 'bg-[#FEF2F2] text-[#EF4444] border-[#EF4444]/20 animate-pulse' : 
                    'bg-[#FFFBEB] text-[#F59E0B] border-[#F59E0B]/20'
                  }`}>
                    {r.verdict} • {r.credibility_score}%
                  </div>
                  <p className="text-[10px] text-[#6EA2B3] font-body font-normal">{new Date(r.generated_at).toLocaleString()}</p>
                </div>
              </div>

              <div className="bg-[#eff6ff] rounded-2xl p-6 mb-6 border border-[#BDD8E9]/50">
                <Label>Executive Summary</Label>
                <p className="text-[#001D39] font-body text-[14px] leading-relaxed">
                  {r.executive_summary}
                </p>
              </div>

              {r.policy_violations?.length > 0 && (
                <div className="space-y-3">
                  <Label>Observed Violations</Label>
                  <div className="flex flex-wrap gap-2">
                    {r.policy_violations.map((v, i) => (
                      <span key={i} className="bg-[#001D39] text-[#BDD8E9] text-[10px] font-black px-3 py-1 rounded-lg uppercase tracking-wider">
                        {typeof v === 'string' ? v : v.type || 'UNKNOWN_BREACH'}
                      </span>
                    ))}
                  </div>
                </div>
              )}
            </div>
          ))
        )}
      </div>
    </div>
  )
}
