# backend/app/services/report_generator.py

"""
PDF Credibility Report builder.
Uses WeasyPrint to generate PDF reports from Claude AI analysis.
"""

from datetime import datetime


def generate_report_html(report_data: dict, session_data: dict) -> str:
    """Generate HTML for the PDF credibility report."""

    verdict = report_data.get('verdict', 'UNDER_REVIEW')
    summary = report_data.get('executive_summary', '')
    red_flags = report_data.get('red_flags', [])
    recommendation = report_data.get('recommendation', '')
    confidence = report_data.get('confidence', 0.0)

    verdict_colors = {
        'CLEAR': '#22C55E',
        'UNDER_REVIEW': '#EAB308',
        'SUSPICIOUS': '#F97316',
        'FLAGGED': '#EF4444'
    }
    color = verdict_colors.get(verdict, '#6B7280')

    flags_html = ''
    for flag in red_flags:
        flags_html += f'''
        <tr>
            <td>{flag.get("timestamp", "N/A")}</td>
            <td>{flag.get("event", "N/A")}</td>
            <td>{flag.get("severity", "N/A")}</td>
            <td>{flag.get("explanation", "N/A")}</td>
        </tr>
        '''

    return f'''
    <!DOCTYPE html>
    <html>
    <head>
        <style>
            body {{ font-family: Arial, sans-serif; padding: 40px; }}
            .header {{ text-align: center; margin-bottom: 30px; }}
            .verdict {{ font-size: 24px; font-weight: bold; color: {color};
                       padding: 10px; border: 2px solid {color}; display: inline-block; }}
            .section {{ margin: 20px 0; }}
            table {{ width: 100%; border-collapse: collapse; }}
            th, td {{ border: 1px solid #ddd; padding: 8px; text-align: left; }}
            th {{ background-color: #1E3A8A; color: white; }}
            .footer {{ margin-top: 30px; font-size: 12px; color: #666; }}
        </style>
    </head>
    <body>
        <div class="header">
            <h1>ExamGuardrail Credibility Report</h1>
            <p>Session: {session_data.get("id", "N/A")}</p>
            <p>Student: {session_data.get("student_name", "N/A")}</p>
            <p>Generated: {datetime.now().strftime("%Y-%m-%d %H:%M:%S")}</p>
            <div class="verdict">{verdict}</div>
        </div>

        <div class="section">
            <h2>Executive Summary</h2>
            <p>{summary}</p>
        </div>

        <div class="section">
            <h2>Score: {session_data.get("credibility_score", "N/A")}/100</h2>
            <p>Confidence: {confidence:.0%}</p>
        </div>

        <div class="section">
            <h2>Red Flags ({len(red_flags)})</h2>
            <table>
                <tr><th>Time</th><th>Event</th><th>Severity</th><th>Explanation</th></tr>
                {flags_html}
            </table>
        </div>

        <div class="section">
            <h2>Recommendation</h2>
            <p>{recommendation}</p>
        </div>

        <div class="footer">
            <p>Generated by ExamGuardrail v1.0.0 — AI-powered by Claude Sonnet</p>
        </div>
    </body>
    </html>
    '''
